//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagement.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:DA_ChuyenNganh/ResortManagement/ResortManagement/Models/TemporarySchedule.cs
    public partial class TemporarySchedule
    {
        public string id { get; set; }
        public string customerId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string serviceId { get; set; }
        public string status { get; set; }
========
    public partial class JobParameter
    {
        public long JobId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Job Job { get; set; }
>>>>>>>> MERGE1:DA_ChuyenNganh/ResortManagement/ResortManagement/Models/JobParameter.cs
    }
}
