//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ResortfEntities : DbContext
    {
        public DB_ResortfEntities()
            : base("name=DB_ResortfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TemporarySchedule> TemporarySchedule { get; set; }
        public virtual DbSet<UsedServices> UsedServices { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
