//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagement.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:DA_ChuyenNganh/ResortManagement/ResortManagement/Models/sysdiagrams.cs
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
========
    public partial class Schema
    {
        public int Version { get; set; }
>>>>>>>> MERGE1:DA_ChuyenNganh/ResortManagement/ResortManagement/Models/Schema.cs
    }
}
