//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.Reviews = new HashSet<Reviews>();
            this.UsedServices = new HashSet<UsedServices>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceCategory { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string ImageRooms { get; set; }
        public string MainImage { get; set; }
        public string Description_check_in { get; set; }
        public string Description_check_out { get; set; }
        public string Description_service_room { get; set; }
        public string Description_bed_type { get; set; }
        public Nullable<int> Description_max_occupancy { get; set; }
        public string Description_room_no_smoke { get; set; }
        public string Description_room_size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedServices> UsedServices { get; set; }
    }
}
